# .env 파일 참조 필요
# 예: 심볼릭 링크 생성(ln -s ../../.env .env)

name: crypto-studio
services:
  db:
    container_name: db
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - cs-net
volumes:
  data-db:
networks:
  cs-net:
    driver: bridge