# .env 파일 생성 후 아래 변수값 명시해야 함
#  - POSTGRES_USER
#  - POSTGRES_PASSWORD
#  - POSTGRES_DB
#  - POSTGRES_PORT

name: crypto-studio-db
services:
  db:
    container_name: db
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  data_db: